# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('roll', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
