# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170430_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createtime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updatetime',
        ),
    ]
